// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: core/grpc_tunnel/grpc_tunnel.proto

package grpc_tunnel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B []byte `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Bytes) Reset() {
	*x = Bytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_grpc_tunnel_grpc_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bytes) ProtoMessage() {}

func (x *Bytes) ProtoReflect() protoreflect.Message {
	mi := &file_core_grpc_tunnel_grpc_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bytes.ProtoReflect.Descriptor instead.
func (*Bytes) Descriptor() ([]byte, []int) {
	return file_core_grpc_tunnel_grpc_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *Bytes) GetB() []byte {
	if x != nil {
		return x.B
	}
	return nil
}

var File_core_grpc_tunnel_grpc_tunnel_proto protoreflect.FileDescriptor

var file_core_grpc_tunnel_grpc_tunnel_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x6e, 0x6e,
	0x65, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x22, 0x15, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x62, 0x32, 0x45, 0x0a, 0x0a, 0x47, 0x52, 0x50, 0x43,
	0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x37, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x74,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_grpc_tunnel_grpc_tunnel_proto_rawDescOnce sync.Once
	file_core_grpc_tunnel_grpc_tunnel_proto_rawDescData = file_core_grpc_tunnel_grpc_tunnel_proto_rawDesc
)

func file_core_grpc_tunnel_grpc_tunnel_proto_rawDescGZIP() []byte {
	file_core_grpc_tunnel_grpc_tunnel_proto_rawDescOnce.Do(func() {
		file_core_grpc_tunnel_grpc_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_grpc_tunnel_grpc_tunnel_proto_rawDescData)
	})
	return file_core_grpc_tunnel_grpc_tunnel_proto_rawDescData
}

var file_core_grpc_tunnel_grpc_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_core_grpc_tunnel_grpc_tunnel_proto_goTypes = []interface{}{
	(*Bytes)(nil), // 0: grpc_tunnel.Bytes
}
var file_core_grpc_tunnel_grpc_tunnel_proto_depIdxs = []int32{
	0, // 0: grpc_tunnel.GRPCTunnel.Connect:input_type -> grpc_tunnel.Bytes
	0, // 1: grpc_tunnel.GRPCTunnel.Connect:output_type -> grpc_tunnel.Bytes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_grpc_tunnel_grpc_tunnel_proto_init() }
func file_core_grpc_tunnel_grpc_tunnel_proto_init() {
	if File_core_grpc_tunnel_grpc_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_grpc_tunnel_grpc_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_grpc_tunnel_grpc_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_grpc_tunnel_grpc_tunnel_proto_goTypes,
		DependencyIndexes: file_core_grpc_tunnel_grpc_tunnel_proto_depIdxs,
		MessageInfos:      file_core_grpc_tunnel_grpc_tunnel_proto_msgTypes,
	}.Build()
	File_core_grpc_tunnel_grpc_tunnel_proto = out.File
	file_core_grpc_tunnel_grpc_tunnel_proto_rawDesc = nil
	file_core_grpc_tunnel_grpc_tunnel_proto_goTypes = nil
	file_core_grpc_tunnel_grpc_tunnel_proto_depIdxs = nil
}
