name: Release simple-tls

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            TAG=${{github.ref_name}}
            REPOSITORY=IrineSistiana/simple-tls
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          context: ./
          file: ./Dockerfile_buildx_actions
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-tls:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-tls:${{github.ref_name}}
